channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==2.3.3
  - pandas==2.3.2
  - pyarrow==18.1.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env